### ISSUE TITLE
First-party / Third-party cookies permissions

### ISSUE THREAD

**Issue by Gitoffthelawn** [clear-code/autopermission#1]
The current implementation only allows for a toggle of the cookie state per site on or off.  Can you add the ability to allow three states per site: on, off, or first-party-only?  Thank you!

**Comment by Gitoffthelawn** [comment]
Any thoughts on this?

**Comment by piroor** [comment]
Currently complete list of possible values for cookies is there.
https://github.com/clear-code/autopermission/blob/master/README.md

Available values for cookie's permission are just same to Firefox's feature itself. See also: http://mxr.mozilla.org/mozilla-central/source/netwerk/cookie/nsICookiePermission.idl#17

**Comment by Gitoffthelawn** [comment]
Thanks so much!
